# Generated by Django 4.1.1 on 2022-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=50)),
                ("value", models.CharField(blank=True, max_length=200)),
                ("HasActive", models.BooleanField()),
            ],
        ),
    ]
